// One-line descriptors for the figure tooltips — display copy only; scoring
// evidence lives in docs/figures/<slug>.md. Keyed by figures.js slug.

export const BLURBS = {
  trump: '45th & 47th President; tariff-first populist at war with the “deep state.”',
  vance: 'Vice President; post-liberal economic populist and crypto champion.',
  miller: 'White House deputy chief of staff; architect of the mass-deportation drive.',
  bannon: 'War Room host; economic-nationalist strategist of the MAGA insurgency.',
  jones: 'Infowars broadcaster; conspiracist of the globalist order.',
  pence: 'Former Vice President; free-trade, faith-first constitutional conservative.',
  romney: 'Retired Utah senator; the institutional Republican conscience.',
  newsom: 'Governor of California; moderating center-left executive.',
  harris: 'Former Vice President; 2024 Democratic nominee.',
  biden: '46th President; institutionalist of the old Democratic order.',
  obama: '44th President; the party’s elder institutionalist statesman.',
  sanders: 'Vermont senator; democratic socialist against the oligarchy.',
  aoc: 'New York congresswoman; standard-bearer of the progressive left.',
  mamdani: 'Mayor of New York; democratic-socialist insurgent turned executive.',
  piker: 'Twitch’s biggest left streamer; Marxist critic of the media order.',
  west: 'Philosopher and 2024 candidate; prophetic-Christian radical.',
  musk: 'World’s richest man; DOGE architect and scourge of the administrative state.',
  rogan: 'Podcast colossus; anti-institutional independent, Trump endorser.',
  cheney: 'Former Wyoming congresswoman; January 6 committee vice-chair in exile.',
  rfk: 'HHS Secretary; MAHA heterodox who fired the vaccine board.',
  paul: 'Kentucky senator; the Senate’s consistent libertarian.',
  pakman: 'Progressive broadcaster; incrementalist defender of the factual order.',
  btc: 'Democratic YouTube messenger; partisan institutionalist.',
  destiny: 'Debate streamer; self-styled “omniliberal” defender of elections.',
  hutch: 'Ex-Call of Duty YouTuber turned pragmatic progressive streamer.',
  pool: 'Timcast host; Occupy journalist turned MAGA-populist skeptic.',
  putin: 'President of Russia; the authoritarian pole of the map.',
  xi: 'General Secretary of the CCP; party-state capitalism personified.',
  desantis: 'Governor of Florida; the culture-war executive.',
  warren: 'Massachusetts senator; wealth-tax progressive, Wall Street’s auditor.',
  buttigieg: 'Former Transportation Secretary; the polished institutional liberal.',
  fetterman: 'Pennsylvania senator; the Democrats’ contrarian in a hoodie.',
  mtg: 'Former Georgia congresswoman; MAGA loyalist turned insurgent apostate.',
  shapiro: 'Daily Wire founder; free-market culture warrior of the old right.',
  kirk: 'Turning Point USA founder (1993–2025); Christian-nationalist organizer.',
  carlson: 'Podcast nationalist; the right’s loudest voice against its own wars.',
  gabbard: 'Former DNI; anti-“deep state” crusader of no fixed party.',
  owens: 'Podcast provocateur; post-MAGA traditionalist conspiracist.',
  maher: 'Real Time host; old-school liberal scourge of the woke.',
  haley: 'Former UN ambassador; the establishment right’s last free-trader.',
  stewart: 'Daily Show host; prosecutor of cable news and donor politics.',
  ramaswamy: 'Ohio gubernatorial front-runner; abolish-the-agencies biotech founder.',
};
