// Minnesota figures, scored against the same 42-item instrument as everyone
// else. Every one is on the 2026 ballot or leaving it: primary day was
// 2026-08-11, and the year's politics are dominated by Operation Metro Surge,
// the federal immigration deployment into the Twin Cities, and the state
// safety-net fraud scandal that ended Walz's re-election bid.
//
// `local: true` marks a figure whose scored record is state-level or
// campaign-level only. Those stay off the national board and appear on the
// Local Leaders roster; the rest appear on both.
//
// Evidence dossiers: docs/figures/<slug>.md. Never hand-edit an (x,y).

export const MN_FIGURES = [
  {
    name: 'Amy Klobuchar',
    slug: 'klobuchar',
    answers: {
      e01: -2, e02: 1, e03: -1, e04: -2, e05: 2, e07: 2, e08: -1, e09: 2,
      e10: -1, e11: 1, e12: -2, e13: -2,
      s01: 2, s02: -2, s03: -2, s04: 0, s05: -2, s06: 2, s07: 1, s08: -1,
      s09: -2, s10: 1, s11: -1, s12: 0, s13: 0,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: -1, y06: -2, y08: -1, y09: 2,
      y10: -2, y11: -1, y12: 2, y13: -2, y14: 2, y15: 1,
      f01: -1, f02: -2, f03: 2,
    },
    note: 'Four-term senator running for governor in 2026 on pragmatism and an anti-fraud plan: a hard no on sweeping tariffs, the Senate\'s leading tech-antitrust author, and loud against the ICE surge while refusing to abolish the agency. Institutionalist almost everywhere the system axis asks, including a record of pressing platforms on health misinformation.',
    sources: [
      { title: 'Klobuchar opposes Trump tariff taxes on the Senate floor', url: 'https://www.klobuchar.senate.gov/public/index.cfm/mobile/news-releases?ID=B1570B31-B899-42DE-98CD-FCD551331A05' },
      { title: 'Klobuchar launches campaign for governor - Minnesota Reformer', url: 'https://minnesotareformer.com/2026/01/29/sen-klobuchar-launches-campaign-for-minnesota-governor/' },
      { title: 'Klobuchar unveils anti-fraud plan - Star Tribune', url: 'https://www.startribune.com/amy-klobuchar-unveils-anti-fraud-plan-in-governor-race-as-she-works-to-distinguish-herself-from-tim-walz/601835267' },
      { title: 'Klobuchar vows to be a transformative governor - MinnPost', url: 'https://www.minnpost.com/elections/2026/06/amy-klobuchar-vows-to-be-a-transformative-minnesota-governor-as-she-vies-for-walzs-seat/' },
      { title: 'Klobuchar launch: "We cannot sugarcoat how hard this is" - CNN', url: 'https://www.cnn.com/2026/01/29/politics/amy-klobuchar-launches-bid-minnesota-governor' },
    ],
  },
  {
    name: 'Angie Craig',
    slug: 'craig',
    answers: {
      e01: -2, e02: 1, e03: -1, e04: -2, e05: 0, e07: 2, e08: 0, e09: 1,
      e10: 0, e11: 1, e12: -1, e13: -2,
      s01: 2, s02: -1, s03: -1, s04: -2, s05: -1, s06: 2, s07: 1, s08: -1,
      s09: -1, s10: 1, s11: 0, s12: 0, s13: 0,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: -1, y06: -1, y08: 0, y09: 1,
      y10: -2, y11: -1, y12: 2, y13: -2, y14: 2, y15: 1,
      f01: -1, f02: 1, f03: 2,
    },
    note: 'Fourth-term House member and Agriculture ranking member who ran for Senate as the moderate: the only Minnesota Democrat to vote for the Laken Riley Act, which she publicly regretted fourteen months later once federal agents surged into Minneapolis. Bipartisan by brand, farm-first on trade, and the pro-Israel side of a primary that turned on Gaza.',
    sources: [
      { title: 'What Craig\'s most controversial vote says about her - Minnesota Reformer', url: 'https://minnesotareformer.com/2026/07/27/what-angie-craigs-most-controversial-vote-says-about-her/' },
      { title: 'Trump\'s immigration crackdown looms over the Senate primary - CBS Minnesota', url: 'https://www.cbsnews.com/minnesota/news/minnesota-democratic-senate-primary-angie-craig-peggy-flanagan-immigration-crackdown/' },
      { title: 'Craig reverses herself on the Laken Riley Act', url: 'https://www.yahoo.com/news/articles/u-rep-angie-craig-reverses-223842194.html' },
      { title: 'Where Craig and Flanagan diverge on the issues - Star Tribune', url: 'https://www.startribune.com/heres-where-democratic-senate-candidates-angie-craig-and-peggy-flanagan-diverge-on-the-issues/601874779' },
      { title: 'Craig voting record - GovTrack', url: 'https://www.govtrack.us/congress/members/angie_craig/412670' },
    ],
  },
  {
    name: 'Peggy Flanagan',
    slug: 'flanagan',
    local: true,
    answers: {
      e01: -2, e02: 2, e03: 2, e04: -2, e05: 1, e07: 2, e08: -1, e09: 2,
      e10: -2, e11: 2, e12: -2, e13: 1,
      s01: 2, s02: -2, s03: -2, s04: 1, s05: -2, s06: 2, s07: 2, s08: -1,
      s09: -2, s10: 2, s11: -2, s12: 1, s13: 2,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: 1, y06: -1, y08: 1, y09: 2,
      y10: -2, y11: 0, y12: 0, y13: -2, y14: 2, y15: 1,
      f01: 1, f02: -2, f03: 1,
    },
    note: 'Lieutenant governor since 2019 and the highest-ranking Native woman in American executive office, running to Craig\'s left with Sanders and Ocasio-Cortez behind her: Medicare for All, a $17 minimum wage, and the flat statement that Israel is committing genocide in Gaza. Movement-left on the issues, but a governing partner rather than an insurgent against the system itself.',
    sources: [
      { title: 'Priorities - Peggy Flanagan for Minnesota', url: 'https://peggyflanagan.com/priorities/' },
      { title: 'Where Craig and Flanagan diverge on the issues - Star Tribune', url: 'https://www.startribune.com/heres-where-democratic-senate-candidates-angie-craig-and-peggy-flanagan-diverge-on-the-issues/601874779' },
      { title: 'Progressive vs moderate showdown tops Minnesota primaries - ABC News', url: 'https://abcnews.com/Politics/progressive-moderate-showdown-senate-seat-tops-minnesota-primaries/story?id=135438391' },
      { title: 'Flanagan on immigration and Craig\'s vote - CBS Minnesota', url: 'https://www.cbsnews.com/minnesota/news/minnesota-democratic-senate-primary-angie-craig-peggy-flanagan-immigration-crackdown/' },
      { title: 'Israel, endorsements and electability dominate the second debate - Star Tribune', url: 'https://www.startribune.com/israel-endorsements-and-electability-dominate-second-us-senate-debate-in-democratic-primary/601870987' },
    ],
  },
  {
    name: 'Keith Ellison',
    slug: 'ellison',
    answers: {
      e01: -2, e02: 2, e03: 2, e04: -2, e05: 2, e07: 2, e08: -2, e09: 2,
      e10: -2, e11: 2, e12: -2, e13: 1,
      s01: 2, s02: -2, s03: -2, s04: 2, s05: -2, s06: 2, s07: 2, s08: -1,
      s09: -2, s10: 2, s11: -2, s12: 2, s13: 2,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: 2, y06: -1, y08: 2, y09: 1,
      y10: -2, y11: 1, y12: 0, y13: -2, y14: 2, y15: 1,
      f01: 0, f02: -2, f03: 1,
    },
    note: 'Attorney general and former DNC deputy chair who says he has sued the Trump administration more than fifty times: the tariff case he won at the Supreme Court, the suit to halt Operation Metro Surge, and the challenge to HHS conditioning funds on a federal definition of sex. Movement-left on economics and civil rights, and the rare figure here who defends the courts and the streets at once.',
    sources: [
      { title: 'Ellison prevails at the Supreme Court on Trump tariffs - MN AG', url: 'https://www.ag.state.mn.us/Office/Communications/2026/02/20_Tariffs.asp' },
      { title: 'Ellison and Minneapolis and Saint Paul sue to halt the ICE surge - MN AG', url: 'https://www.ag.state.mn.us/Office/Communications/2026/01/12_ICE.asp' },
      { title: 'Ellison sues over funding conditioned on discrimination - MN AG', url: 'https://www.ag.state.mn.us/Office/Communications/2026/01/16_HHS.asp' },
      { title: '"Feels like a cover-up": Ellison on the deadly ICE crackdown - Democracy Now', url: 'https://www.democracynow.org/2026/1/27/minnesota_attorney_general_keith_ellison' },
      { title: 'Trump suit to compel state immigration enforcement dismissed - MN AG', url: 'https://www.ag.state.mn.us/Office/Communications/2026/07/21_Sanctuary-Laws.asp' },
    ],
  },
  {
    name: 'Tim Walz',
    slug: 'walz',
    answers: {
      e01: -2, e02: 1, e03: 1, e04: -2, e05: 0, e07: 2, e08: -1, e09: 2,
      e10: -1, e11: 2, e12: -2, e13: 1,
      s01: 2, s02: -2, s03: -2, s04: 0, s05: -2, s06: 2, s07: 2, s08: -1,
      s09: -2, s10: 2, s11: -2, s12: 0, s13: 2,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: 0, y06: -1, y08: 0, y09: 2,
      y10: -2, y11: -1, y12: 1, y13: -2, y14: 2, y15: 1,
      f01: -1, f02: -1, f03: 2,
    },
    note: 'Two-term governor and the 2024 vice-presidential nominee, leaving office after a safety-net fraud scandal ended his re-election bid. Scored on the 2023 trifecta record he signed (paid leave, 100% clean energy by 2040, legal marijuana, red-flag and background-check laws, trans refuge) and on 2026, when he put the National Guard on alert against a federal immigration deployment and told Minnesotans to film ICE agents.',
    sources: [
      { title: 'Walz puts the National Guard on alert amid ICE protests - The Hill', url: 'https://thehill.com/homenews/state-watch/5680129-walz-authorizes-national-guard/' },
      { title: 'Walz encourages Minnesotans to film ICE agents for future prosecutions', url: 'https://www.yahoo.com/news/articles/gov-tim-walz-encourages-minnesotans-024702159.html' },
      { title: '2025-26 Minnesota ICE deployment (Operation Metro Surge) - Britannica', url: 'https://www.britannica.com/event/2025-26-Minnesota-ICE-Deployment' },
      { title: 'Walz written testimony to House Oversight, March 2026', url: 'https://oversight.house.gov/wp-content/uploads/2026/03/Walz-Written-Testimony.pdf' },
      { title: 'Walz record, fraud scandal, and 2026 exit', url: 'https://legalclarity.org/tim-walz-for-governor-record-fraud-scandal-and-2026-exit/' },
    ],
  },
  {
    name: 'Lisa Demuth',
    slug: 'demuth',
    local: true,
    answers: {
      e01: 0, e02: -2, e03: -2, e04: 1, e05: 0, e07: -1, e08: 0, e09: -1,
      e10: 1, e11: -1, e12: 2, e13: -2,
      s01: -2, s02: 2, s03: 2, s04: -2, s05: 1, s06: 0, s07: -2, s08: 1,
      s09: 1, s10: -1, s11: 2, s12: 0, s13: -2,
      y01: -1, y02: 1, y03: -1, y04: 0, y05: -2, y06: 1, y08: 0, y09: -1,
      y10: 0, y11: -1, y12: 1, y13: -2, y14: 0, y15: 0,
      f01: 0, f02: 2, f03: 0,
    },
    note: 'Speaker of the Minnesota House, the first Black person and first Republican woman to hold the gavel, running for governor as the competence candidate against Walz\'s fraud record: lower taxes, tougher on crime, repeal the nuclear ban, protect girls\' sports. Conservative on the issues but institutional in method, having governed through a tied chamber, with one insurgent note in staying in the race over convention voting-machine irregularities.',
    sources: [
      { title: 'Demuth announces run for governor - Star Tribune', url: 'https://www.startribune.com/minnesota-house-speaker-lisa-demuth-announces-run-for-governor/601512664' },
      { title: 'A look at the GOP candidates for governor - MinnPost', url: 'https://www.minnpost.com/elections/2026/08/i-dont-trust-any-election-ever-done-with-a-computer-a-look-at-the-gop-candidates-for-minnesota-governor-mike-lindell-lisa-demuth-kendall-qualls/' },
      { title: 'Lisa Demuth - Ballotpedia', url: 'https://ballotpedia.org/Lisa_Demuth' },
      { title: 'Demuth record: abortion ban authorship and 2023 votes - A Better Minnesota', url: 'https://abetterminnesota.org/2025/11/lisa-demuth-is-wrong-for-minnesota/' },
      { title: 'Demuth picks a running mate - CBS Minnesota', url: 'https://www.cbsnews.com/minnesota/news/lisa-demuth-ryan-wilson-running-mate-gubernatorial-race' },
    ],
  },
  {
    name: 'Brad Finstad',
    slug: 'finstad',
    local: true,
    answers: {
      e01: 1, e02: -2, e03: -2, e04: 2, e05: 0, e07: -1, e08: 1, e09: -1,
      e10: 2, e11: -2, e12: 2, e13: -2,
      s01: -2, s02: 2, s03: 2, s04: -2, s05: 1, s06: 1, s07: -2, s08: 2,
      s09: 2, s10: -1, s11: 2, s12: 1, s13: -2,
      y01: -1, y02: 0, y03: 0, y04: 1, y05: -2, y06: 1, y08: 0, y09: -1,
      y10: 1, y11: -1, y12: 1, y13: -2, y14: 0, y15: 0,
      f01: 1, f02: 2, f03: -2,
    },
    note: 'Third-term First District Republican and former USDA state director who votes with his party and district both: for the tariffs that hurt his own soybean growers, against every Ukraine aid package while voting Israel aid through, 100% pro-life, and pushing to replace the farm guest-worker system he calls archaic. Institutional in style, and the farm bill he keeps promising has not arrived.',
    sources: [
      { title: 'Finstad and Johnson split over farm policy at Farmfest - Agweek', url: 'https://www.agweek.com/news/policy/rep-brad-finstad-and-dfl-challenger-jake-johnson-split-over-farm-policy-at-farmfest' },
      { title: 'Finstad backed Trump tariffs as Minnesota farmers paid the price', url: 'https://americanjournalnews.com/finstad-backed-trump-tariffs-as-minnesota-farmers-paid-the-price/' },
      { title: 'Finstad voted against Ukraine aid - Winona County DFL', url: 'https://winonadfl.org/2024/05/09/finstad-against-aid-for-ukraine/' },
      { title: 'Finstad votes to protect the right to life - office press release', url: 'https://www.legistorm.com/stormfeed/view_rss/2180402/member/3611/title/finstad-votes-to-protect-the-right-to-life.html' },
      { title: 'Finstad voting record - GovTrack', url: 'https://www.govtrack.us/congress/members/brad_finstad/456869' },
    ],
  },
  {
    name: 'Jake Johnson',
    slug: 'jakejohnson',
    local: true,
    answers: {
      e01: -2, e02: 1, e03: 1, e04: -2, e05: 2, e07: 2, e08: 0, e09: 2,
      e10: 0, e11: 1, e12: -2, e13: 0,
      s01: 2, s02: -1, s03: -1, s04: 0, s05: -1, s06: 1, s07: 1, s08: 0,
      s09: -1, s10: 1, s11: -1, s12: 0, s13: 0,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: 0, y06: 0, y08: 1, y09: 1,
      y10: -2, y11: 0, y12: 1, y13: -2, y14: 2, y15: 1,
      f01: 0, f02: 0, f03: 1,
    },
    note: 'Rochester high-school math teacher and union leader challenging Finstad in a red district, running a small-dollar campaign on costs, corruption, and consolidation: break up the buyers who set farm prices, restore the export markets tariffs gutted, defend Social Security and Medicare. Rural-Democratic on guns, supporting the right while backing background checks and red-flag laws.',
    sources: [
      { title: 'Finstad and Johnson split over farm policy at Farmfest - Agweek', url: 'https://www.agweek.com/news/policy/rep-brad-finstad-and-dfl-challenger-jake-johnson-split-over-farm-policy-at-farmfest' },
      { title: 'A teacher tries to solve the difficult math in a red district - MinnPost', url: 'https://www.minnpost.com/elections/2026/08/democrat-jake-johnson-a-teacher-tries-to-solve-the-difficult-math-in-a-red-district/' },
      { title: 'Can Jake Johnson pull off an upset in Minnesota\'s 1st? - Post Bulletin', url: 'https://www.postbulletin.com/news/local/can-jake-johnson-pull-off-an-upset-in-minnesotas-1st' },
      { title: 'Johnson campaign launch: fight for working people', url: 'https://www.jakejohnsonforcongress.com/news/news-2' },
      { title: 'Jake Johnson (Minnesota) - Ballotpedia', url: 'https://ballotpedia.org/Jake_Johnson_(Minnesota)' },
    ],
  },
  {
    name: 'Michele Tafoya',
    slug: 'tafoya',
    local: true,
    answers: {
      e01: 1, e02: -2, e03: -2, e04: 2, e05: 0, e07: -1, e08: 1, e09: -1,
      e10: 2, e11: -1, e12: 2, e13: -2,
      s01: 0, s02: 2, s03: 1, s04: -2, s05: 1, s06: 0, s07: -2, s08: 1,
      s09: 1, s10: 0, s11: 2, s12: 0, s13: -2,
      y01: -2, y02: 0, y03: 0, y04: 1, y05: -2, y06: 2, y08: 1, y09: -1,
      y10: 1, y11: -1, y12: 0, y13: -2, y14: 0, y15: 1,
      f01: 0, f02: 2, f03: -1,
    },
    note: 'Thirty-year NBC sideline reporter turned conservative commentator and now the Republican Senate nominee, built on opposition to transgender athletes in women\'s sports and on attacking Minnesota Democrats over safety-net fraud. Heterodox where it counts against her party base: pro-choice to twelve weeks, and on record in 2022 hoping Trump would not run again before endorsing him and donating dozens of times.',
    sources: [
      { title: 'Tafoya secures the GOP nomination for U.S. Senate - The Center Square', url: 'https://www.thecentersquare.com/minnesota/article_c6bbd054-7423-41f0-8da8-c1a614f9c0ec.html' },
      { title: 'Tafoya\'s star power faces a conservative test - Star Tribune', url: 'https://www.startribune.com/mn-senate-republican-gop-candidates-tuesday-primary-election-tafoya-schwarze-white/601874785' },
      { title: 'Tafoya has national GOP support, but state activists are a challenge - MinnPost', url: 'https://www.minnpost.com/national/washington/2026/05/michele-tafoya-has-support-of-national-gop-but-winning-over-state-activists-challenge/' },
      { title: 'Former broadcaster launches Senate bid - Star Tribune', url: 'https://www.startribune.com/michele-tafoya-mn-senate/601567897' },
      { title: 'Michele Tafoya - Ballotpedia', url: 'https://ballotpedia.org/Michele_Tafoya' },
    ],
  },
  {
    name: 'Mike Lindell',
    slug: 'lindell',
    answers: {
      e01: 2, e02: -2, e03: -2, e04: 2, e05: 1, e07: -2, e08: 1, e09: -1,
      e10: 2, e11: -2, e12: 2, e13: -2,
      s01: -2, s02: 2, s03: 2, s04: -2, s05: 2, s06: -1, s07: -2, s08: 2,
      s09: 2, s10: -1, s11: 2, s12: 1, s13: -2,
      y01: -2, y02: -2, y03: 2, y04: 2, y05: 0, y06: 2, y08: 1, y09: -2,
      y10: 2, y11: 1, y12: -1, y13: 1, y14: -2, y15: 2,
      f01: 1, f02: 1, f03: -2,
    },
    note: 'MyPillow founder, Trump-endorsed candidate for governor, and the country\'s most persistent election denier, who resigned as CEO to run on a 73-page plan to eliminate the state income tax. Two courts have now found he defamed election-technology figures, and he has not moved an inch: he does not trust any election run on a computer, and says so on primary day itself.',
    sources: [
      { title: '"I don\'t trust any election ever done with a computer" - MinnPost', url: 'https://www.minnpost.com/elections/2026/08/i-dont-trust-any-election-ever-done-with-a-computer-a-look-at-the-gop-candidates-for-minnesota-governor-mike-lindell-lisa-demuth-kendall-qualls/' },
      { title: 'Lindell announces a run for governor - CBS Minnesota', url: 'https://www.cbsnews.com/minnesota/news/mike-lindell-minnesota-governor-republican-campaign-mypillow/' },
      { title: 'One-on-one with gubernatorial candidate Mike Lindell - KTTC', url: 'https://www.kttc.com/2026/05/15/one-on-one-with-minnesota-gubernatorial-candidate-mike-lindell/' },
      { title: 'MyPillow founder and Trump ally to run for governor - PBS NewsHour', url: 'https://www.pbs.org/newshour/amp/politics/mypillow-founder-and-trump-ally-mike-lindell-to-run-for-minnesota-governor-in-2026' },
      { title: 'Lindell in the Reformer over the years - Minnesota Reformer', url: 'https://minnesotareformer.com/2026/07/28/best-of-frenemies-mike-lindell-in-the-reformer-over-the-years/' },
    ],
  },
];
