// The 2028 bench: figures most often named for the next presidential cycle who
// were not already on the board. Scored against the same 42-item instrument.
// The bench roster in modes.js also pulls in figures scored elsewhere (Vance,
// Newsom, Harris, Buttigieg, DeSantis, Haley, Ramaswamy, Ocasio-Cortez, Walz,
// Klobuchar), so this file holds only the additions.
//
// Evidence dossiers: docs/figures/<slug>.md. Never hand-edit an (x,y).

export const BENCH_FIGURES = [
  {
    name: 'Marco Rubio',
    slug: 'rubio',
    answers: {
      e01: 2, e02: -2, e03: -2, e04: 2, e05: 0, e07: -1, e08: 1, e09: -1,
      e10: 2, e11: -2, e12: 2, e13: -2,
      s01: -2, s02: 2, s03: 2, s04: -2, s05: 2, s06: -1, s07: -2, s08: 2,
      s09: 2, s10: -1, s11: 2, s12: 1, s13: -2,
      y01: -1, y02: 0, y03: 1, y04: 2, y05: -2, y06: 0, y08: 0, y09: -1,
      y10: 1, y11: -1, y12: 0, y13: -1, y14: 0, y15: 0,
      f01: 0, f02: 2, f03: -1,
    },
    note: 'Secretary of State and national security adviser at once, a concentration held before only by Kissinger, and the administration\'s most powerful survivor. Scored on the conversion rather than the old career: the Gang of Eight author who now denounces mass migration and ended Venezuelan TPS, the hawk who runs the Venezuela operation while calling Ukraine "not our war."',
    sources: [
      { title: 'Rubio on the 2026 TIME100 list', url: 'https://time.com/collection/100-most-influential-people/2026/marco-rubio/' },
      { title: 'Rubio juggles two roles in the administration - NPR', url: 'https://www.npr.org/2026/01/26/nx-s1-5668228/greenland-iran-venezuela-marco-rubio-ukraine-foreign-policy' },
      { title: 'Once a champion for Venezuelans, Rubio endorses ending TPS', url: 'https://www.yahoo.com/news/once-champion-venezuelans-rubio-endorses-220038340.html' },
      { title: 'Five takeaways from Rubio\'s year-end briefing - Al Jazeera', url: 'https://www.aljazeera.com/news/2025/12/19/five-key-takeaways-from-us-secretary-of-state-rubios-year-end-briefing' },
      { title: 'Rubio emerges as a key power player after the Venezuela operation - Fox News', url: 'https://www.foxnews.com/politics/marco-rubio-emerges-key-trump-power-player-after-venezuela-operation.amp' },
    ],
  },
  {
    name: 'Josh Hawley',
    slug: 'hawley',
    answers: {
      e01: 2, e02: -1, e03: 0, e04: -2, e05: 2, e07: 1, e08: -1, e09: 1,
      e10: 1, e11: -2, e12: 0, e13: -1,
      s01: -2, s02: 2, s03: 2, s04: -2, s05: 2, s06: -2, s07: -2, s08: 2,
      s09: 2, s10: -1, s11: 2, s12: 1, s13: -2,
      y01: -2, y02: -2, y03: 1, y04: 2, y05: 0, y06: 2, y08: 2, y09: -2,
      y10: 2, y11: 1, y12: -1, y13: -1, y14: 0, y15: 2,
      f01: 1, f02: 2, f03: -1,
    },
    note: 'The Senate\'s working experiment in economic populism from the right: co-sponsored a minimum-wage increase with a Democrat, walks picket lines, wrote the book against big tech, and moved to repeal the Medicaid provisions of a bill he had just voted for. Hard-right on every social and system item, including the 2020 certification objection, which is why the economic heterodoxy barely moves him left.',
    sources: [
      { title: 'Hawley irks Republicans as he carves out a lane - NBC News', url: 'https://www.nbcnews.com/politics/congress/sen-josh-hawley-irks-republicans-tries-carve-out-lane-rcna222025' },
      { title: 'Hawley op-ed: Don\'t cut Medicaid', url: 'https://www.hawley.senate.gov/hawley-op-ed-dont-cut-medicaid/' },
      { title: 'Hawley teams with a Democrat on the federal minimum wage', url: 'https://www.stltoday.com/news/local/column/joe-holleman/article_e24430bf-fcfc-4423-80a9-7026362b61d9.html' },
      { title: 'Hawley tries to sell unions to Republicans - NOTUS', url: 'https://www.notus.org/economy/josh-hawley-sell-unions-republicans-not-working' },
      { title: 'Hawley on the megabill Medicaid cuts - NBC News', url: 'https://www.nbcnews.com/politics/congress/trump-megabill-vote-medicaid-josh-hawley-republican-rcna217596' },
    ],
  },
  {
    name: 'Glenn Youngkin',
    slug: 'youngkin',
    answers: {
      e01: -1, e02: -2, e03: -2, e04: 2, e05: 0, e07: -1, e08: 1, e09: -2,
      e10: 2, e11: -1, e12: 2, e13: -2,
      s01: -1, s02: 2, s03: 1, s04: -2, s05: 1, s06: 1, s07: -2, s08: 2,
      s09: 1, s10: -1, s11: 2, s12: 0, s13: -2,
      y01: 0, y02: 0, y03: -1, y04: 0, y05: -2, y06: 1, y08: 0, y09: 0,
      y10: 0, y11: -1, y12: 1, y13: -2, y14: 0, y15: 0,
      f01: -1, f02: 2, f03: 1,
    },
    note: 'Private-equity governor of Virginia through January 2026, who won on parents\' rights and school curriculum and governed as a corporate tax-cutter: grocery tax repeal, a fifteen-week abortion limit he could not pass, mask-mandate and transgender-schools directives. The one genuinely unresolved item is elections, where he spent four years addressing both the Trump and the never-Trump halves of his party without settling either.',
    sources: [
      { title: 'Glenn Youngkin - Ballotpedia', url: 'https://ballotpedia.org/Glenn_Youngkin' },
      { title: 'Glenn Youngkin - Wikipedia', url: 'https://en.wikipedia.org/wiki/Glenn_Youngkin' },
      { title: 'Youngkin straddling the GOP election divide - Fox News', url: 'https://www.foxnews.com/media/washington-post-reporter-rips-glenn-youngkin-straddling-gop-big-lie-divide' },
      { title: 'Youngkin\'s political future and the abortion limit', url: 'https://news.yahoo.com/virginia-gov-glenn-youngkin-political-011037473.html' },
      { title: 'Why the Virginia governor draws challenger talk - Forbes', url: 'https://www.forbes.com/sites/brianbushard/2023/09/28/glenn-youngkin-buzz-heres-why-everyone-is-suddenly-talking-about-the-virginia-governor-as-a-trump-challenger/' },
    ],
  },
  {
    name: 'Brian Kemp',
    slug: 'kemp',
    answers: {
      e01: -1, e02: -2, e03: -2, e04: 2, e05: 0, e07: -1, e08: 1, e09: -2,
      e10: 2, e11: -1, e12: 2, e13: -2,
      s01: -2, s02: 2, s03: 2, s04: -2, s05: 2, s06: 0, s07: -2, s08: 2,
      s09: 2, s10: -1, s11: 2, s12: 1, s13: -2,
      y01: 0, y02: 2, y03: -2, y04: 0, y05: -2, y06: 1, y08: 0, y09: 0,
      y10: -1, y11: -2, y12: 1, y13: -2, y14: 1, y15: 0,
      f01: 0, f02: 2, f03: 1,
    },
    note: 'Georgia governor and the clearest case on the board of a hard-right issue record paired with a hard institutionalist system record: the heartbeat law, permitless carry, and a standing refusal to expand Medicaid, alongside the refusal to call a session to overturn 2020 that made him a Trump target and then a survivor of one.',
    sources: [
      { title: 'Trump once targeted Kemp; now he is steering what comes next', url: 'https://newschannel9.com/news/local/trump-once-targeted-kemp-now-the-georgia-governor-is-trying-to-steer-what-comes-next' },
      { title: 'Brian Kemp - Ballotpedia', url: 'https://ballotpedia.org/Brian_Kemp' },
      { title: 'Youngkin campaigns with Kemp - CBS News', url: 'https://www.cbsnews.com/news/glenn-youngkin-campaign-trail-brian-kemp-georgia-2022-midterm-elections' },
      { title: '2028 presidential candidates - Ballotpedia', url: 'https://ballotpedia.org/Presidential_candidates,_2028' },
      { title: 'Potential 2028 contenders on the trail - NBC News', url: 'https://www.nbcnews.com/politics/elections/potential-2028-presidential-contenders-hit-trail-years-big-campaigns-rcna238144' },
    ],
  },
  {
    name: 'Josh Shapiro',
    slug: 'jshapiro',
    answers: {
      e01: -2, e02: 1, e03: 0, e04: -2, e05: 0, e07: 1, e08: 0, e09: 2,
      e10: -1, e11: 1, e12: -1, e13: -1,
      s01: 2, s02: -2, s03: -1, s04: -1, s05: -1, s06: 2, s07: 1, s08: 0,
      s09: -1, s10: 1, s11: -1, s12: 0, s13: 0,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: -1, y06: -1, y08: 0, y09: 1,
      y10: -2, y11: -1, y12: 2, y13: -2, y14: 2, y15: 1,
      f01: -1, f02: 1, f03: 2,
    },
    note: 'Pennsylvania governor and former attorney general, running for a second term in a state Trump carried, and openly interested in "being part of that conversation" about 2028. Deal-making institutionalist: went to the Trump White House to press PJM on electricity capacity in the same season he said the tariffs were looking to screw over Pennsylvania farmers.',
    sources: [
      { title: 'Shapiro\'s White House trip on electricity prices - Washington Examiner', url: 'https://www.washingtonexaminer.com/news/white-house/4422285/josh-shapiro-white-house-trip-electricity-prices-help-2026-2028/' },
      { title: '2028 Democratic contenders and MAGA heirs emerge - The Hill', url: 'https://thehill.com/homenews/campaign/5830577-potential-presidential-bids-2028/' },
      { title: 'Trump appoints Shapiro, Whitmer, Moore and DeSantis to the Council of Governors', url: 'https://uptownstandard.com/2025/02/21/president-trump-appoints-josh-shapiro-gretchen-whitmer-wes-moore-and-ron-desantis-to-the-council-of-governors-shaping-the-future-of-the-2028-presidential-election/' },
      { title: '2028 Democratic presidential hopefuls - The Hill', url: 'https://thehill.com/homenews/campaign/5661026-democratic-party-future-leaders/' },
      { title: '2028 United States presidential election - Wikipedia', url: 'https://en.wikipedia.org/wiki/2028_United_States_presidential_election' },
    ],
  },
  {
    name: 'Gretchen Whitmer',
    slug: 'whitmer',
    answers: {
      e01: -1, e02: 1, e03: 0, e04: -2, e05: 0, e07: 2, e08: 0, e09: 2,
      e10: -1, e11: 1, e12: -1, e13: -1,
      s01: 2, s02: -2, s03: -2, s04: 0, s05: -1, s06: 2, s07: 1, s08: -1,
      s09: -1, s10: 2, s11: -1, s12: 0, s13: 0,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: -1, y06: -1, y08: 0, y09: 2,
      y10: -2, y11: -1, y12: 2, y13: -2, y14: 2, y15: 1,
      f01: 0, f02: 0, f03: 1,
    },
    note: 'Michigan governor who took the opposite bet from Pritzker: repeated Oval Office meetings to press for tariff relief and Medicaid money, and rare public praise from Trump in return. "I\'m not against tariffs outright, but it is a blunt tool." Standard Democratic issue positions with an auto-state accent, and the most cooperative system-axis record of the Democratic bench.',
    sources: [
      { title: 'Whitmer bucks the Democratic playbook on tariffs - Fox News', url: 'https://www.foxnews.com/politics/whitmer-ditches-dem-playbook-response-trumps-tariffs-amid-2028-speculation' },
      { title: 'Whitmer meets Trump to press on tariffs and Medicaid cuts - CBS News', url: 'https://www.cbsnews.com/news/gretchen-whitmer-meets-trump-tariffs-medicaid/' },
      { title: 'Whitmer wants to find common ground with Trump', url: 'https://www.yahoo.com/news/michigan-gov-gretchen-whitmer-potential-053441801.html' },
      { title: 'Trump offers rare praise for Whitmer in the Oval Office', url: 'https://www.yahoo.com/news/michigan-democratic-gov-whitmer-strays-150247011.html' },
      { title: 'Whitmer fell into the tariff trap - The New Republic', url: 'https://newrepublic.com/post/193888/gretchen-whitmer-trump-tariff-trap' },
    ],
  },
  {
    name: 'Wes Moore',
    slug: 'moore',
    answers: {
      e01: -2, e02: 1, e03: 1, e04: -2, e05: 0, e07: 2, e08: 0, e09: 2,
      e10: 0, e11: 2, e12: -1, e13: 0,
      s01: 2, s02: -2, s03: -2, s04: 0, s05: -1, s06: 2, s07: 2, s08: 0,
      s09: -1, s10: 2, s11: -2, s12: 1, s13: 0,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: 0, y06: -1, y08: 0, y09: 1,
      y10: -2, y11: -1, y12: 1, y13: -2, y14: 2, y15: 1,
      f01: -1, f02: 0, f03: 2,
    },
    note: 'Maryland governor, combat veteran, and the bench member who keeps saying he is not running: a service-year program, mass pardons for marijuana convictions, and a child-poverty agenda, paired with the flat 2026 line "I\'m not running" for president. Progressive on the issues and conventional on the system axis.',
    sources: [
      { title: 'Wes Moore: "I\'m not running" for president in 2028', url: 'https://www.yahoo.com/news/wes-moore-m-not-running-161732299.html' },
      { title: 'How Trump is molding 2028 Democratic contenders like Moore', url: 'https://thedailyrecord.com/2025/12/31/democratic-governors-trump-opposition-2028-election/' },
      { title: 'Trump appoints Shapiro, Whitmer, Moore and DeSantis to the Council of Governors', url: 'https://uptownstandard.com/2025/02/21/president-trump-appoints-josh-shapiro-gretchen-whitmer-wes-moore-and-ron-desantis-to-the-council-of-governors-shaping-the-future-of-the-2028-presidential-election/' },
      { title: 'Potential 2028 contenders on the trail - NBC News', url: 'https://www.nbcnews.com/politics/elections/potential-2028-presidential-contenders-hit-trail-years-big-campaigns-rcna238144' },
      { title: '2028 Democratic presidential hopefuls - The Hill', url: 'https://thehill.com/homenews/campaign/5661026-democratic-party-future-leaders/' },
    ],
  },
  {
    name: 'Andy Beshear',
    slug: 'beshear',
    answers: {
      e01: -2, e02: 1, e03: 0, e04: -2, e05: 0, e07: 1, e08: 0, e09: 2,
      e10: -1, e11: 0, e12: -1, e13: -1,
      s01: 1, s02: -1, s03: -1, s04: -1, s05: -1, s06: 1, s07: 0, s08: 0,
      s09: -1, s10: 1, s11: -1, s12: 0, s13: 0,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: -1, y06: -1, y08: 0, y09: 1,
      y10: -2, y11: -2, y12: 2, y13: -2, y14: 2, y15: 1,
      f01: 0, f02: 0, f03: 1,
    },
    note: 'Twice-elected Democratic governor of a state Trump won by thirty points and chair of the Democratic Governors Association, making the big-tent case for 2026 while eyeing 2028. Vetoed the transgender care ban and the abortion restrictions his legislature overrode, called the deployment of troops to American cities un-American, and otherwise governs by working with the Republicans who hold both chambers.',
    sources: [
      { title: 'Beshear denounces the "un-American" deployment of military to US cities - Kentucky Lantern', url: 'https://kentuckylantern.com/2025/10/09/beshear-denounces-trumps-un-american-deployment-of-military-to-u-s-cities/' },
      { title: 'Beshear won twice in Trump country and wants to show Democrats how', url: 'https://www.ms.now/news/andy-beshear-2028-midterms-interview' },
      { title: '2028 Democratic presidential hopefuls - The Hill', url: 'https://thehill.com/homenews/campaign/5661026-democratic-party-future-leaders/' },
      { title: '2028 Democratic contenders and MAGA heirs emerge - The Hill', url: 'https://thehill.com/homenews/campaign/5830577-potential-presidential-bids-2028/' },
      { title: '2028 United States presidential election - Wikipedia', url: 'https://en.wikipedia.org/wiki/2028_United_States_presidential_election' },
    ],
  },
  {
    name: 'JB Pritzker',
    slug: 'pritzker',
    answers: {
      e01: -2, e02: 2, e03: 2, e04: -2, e05: 0, e07: 2, e08: 0, e09: 2,
      e10: -1, e11: 2, e12: -2, e13: 0,
      s01: 2, s02: -2, s03: -2, s04: 0, s05: -2, s06: 2, s07: 2, s08: -1,
      s09: -2, s10: 2, s11: -2, s12: 2, s13: 2,
      y01: 1, y02: 2, y03: -2, y04: -2, y05: 1, y06: -1, y08: 0, y09: 2,
      y10: -2, y11: 0, y12: -1, y13: -2, y14: 2, y15: 1,
      f01: 0, f02: 0, f03: 2,
    },
    note: 'Illinois governor and the confrontation wing of the Democratic bench: refused the ultimatum to call up the Guard for federal deployments into Chicago, called it outrageous and un-American, and got called a slob by the White House for it. Progressive across the issue axes and the one Democratic governor here who explicitly rejects the both-sides-can-work-together frame.',
    sources: [
      { title: 'Pritzker is a hard no on the National Guard - NPR', url: 'https://www.northcountrypublicradio.org/news/npr/g-s1-89190/tennessee-s-governor-welcomed-the-national-guard-illinois-jb-pritzker-is-a-hard-no' },
      { title: 'White House authorizes Guard deployment to Illinois - NBC News', url: 'https://www.nbcnews.com/politics/trump-administration/chicago-national-guard-trump-deployment-portland-rcna235625' },
      { title: 'Trump official mocks Pritzker amid the Guard battle - Newsweek', url: 'https://www.newsweek.com/jb-pritzker-illinois-chicago-national-guard-update-10835174' },
      { title: 'Pritzker on Trump and troops in Chicago - NPR', url: 'https://www.npr.org/2025/09/10/nx-s1-5533120/pritzker-trump-chicago-troops' },
      { title: '2028 Democratic presidential hopefuls - The Hill', url: 'https://thehill.com/homenews/campaign/5661026-democratic-party-future-leaders/' },
    ],
  },
];
